version: "3.8"
services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./:/src
    ports:
      - "8001:8001"
    depends_on: []

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://backend:8001
    depends_on:
      - backend
